### ISSUE TITLE
action이 뜻하는것은 무엇인가요??

### ISSUE THREAD

**Issue by yevgnenll** [uwangg/PilotProject#2]
java  + spring boot 만 사용해봐서

action이라는 개념이 생소한데 comment로 가르쳐주시면 감사하겠습니다 :)

**Comment by uwangg** [comment]
클라이언트에서 요청을 받을때 요청을 처리해줄 객체들이 필요한데
각각의 요청을 처리해주는걸 action이라고 뒀습니다!
action이 많다보니 먼저 하나의 servlet을 둬서 그 servlet에서 먼저 요청을 받고 요청에 맞는 action객체로 나누어 주는 방식으로 하고있습니다~

**Comment by yevgnenll** [comment]
html -> servlet -> controller -> action -> dao 이렇게 가는건가요?

**Comment by uwangg** [comment]
view(html,jsp) -> controller(servlet->action) -> model (vo,dao) 입니다~!
